const fs = require('fs');
const path = require('path');
const { withDangerousMod, withAndroidManifest, AndroidConfig } = require('expo/config-plugins');

/**
 * Expo config plugin for `react-native-hce` (Android Host Card Emulation).
 *
 * This is what lets the Cappy app on an Android phone emulate an NFC Type 4
 * tag containing a family-invite link, so a second phone (iOS or Android)
 * can tap it directly — no physical sticker, no pairing step. Apple's
 * CoreNFC has no equivalent third-party API, so this only ever runs on
 * Android; the plugin is a no-op for the iOS build.
 *
 * `react-native-hce`'s own README documents these as manual post-install
 * steps for bare RN projects (see https://github.com/appidea/react-native-hce#post-installation-steps).
 * Since Cappy is an Expo-managed project whose `android/` folder is
 * regenerated by `expo prebuild` / EAS Build, we apply them as a config
 * plugin instead so they survive every prebuild:
 *
 *   1. `android/app/src/main/res/xml/aid_list.xml` — declares the NFC
 *      Forum "NDEF Application" AID (D2760000850101) this app emulates.
 *   2. `AndroidManifest.xml` — the `android.hardware.nfc.hce` uses-feature,
 *      plus the `CardService` <service> the library ships, wired to the
 *      HOST_APDU_SERVICE intent-filter and pointed at the aid_list above.
 */

const AID_LIST_CONTENTS = `<?xml version="1.0" encoding="utf-8"?>
<host-apdu-service xmlns:android="http://schemas.android.com/apk/res/android"
                   android:description="@string/app_name"
                   android:requireDeviceUnlock="false">
  <aid-group android:category="other"
             android:description="@string/app_name">
    <!-- NFC Forum "NDEF Application" AID — makes the emulated tag readable
         by any standard NFC Forum Type 4 Tag reader (iOS CoreNFC included),
         not just other Cappy devices. -->
    <aid-filter android:name="D2760000850101" />
  </aid-group>
</host-apdu-service>
`;

const CARD_SERVICE_NAME = 'com.reactnativehce.services.CardService';

const withAidListXml = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/res/xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'aid_list.xml'), AID_LIST_CONTENTS, 'utf-8');
      return cfg;
    },
  ]);

const withHceManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    // `<uses-feature android:name="android.hardware.nfc.hce" .../>`
    //
    // `required="false"` is deliberate: HCE only backs the "tap to send a
    // family invite" convenience feature (src/nfc/hceBroadcast.ts already
    // no-ops gracefully when it's unavailable). The core, must-work flow —
    // scanning a medication sticker to log a dose — only needs standard
    // NFC read support, which is far more common than HCE. Marking this
    // `required="true"` would make Android's package manager (and the Play
    // Store) refuse to install the app at all on any tester's phone that
    // lacks HCE hardware, which is too strict for what is an optional,
    // non-core feature.
    manifest['uses-feature'] = manifest['uses-feature'] ?? [];
    const hasHceFeature = manifest['uses-feature'].some(
      (f) => f.$?.['android:name'] === 'android.hardware.nfc.hce',
    );
    if (!hasHceFeature) {
      manifest['uses-feature'].push({
        $: { 'android:name': 'android.hardware.nfc.hce', 'android:required': 'false' },
      });
    }

    // The `CardService` HostApduService that react-native-hce ships,
    // registered against the standard HOST_APDU_SERVICE action so Android's
    // HCE router dispatches taps to it.
    const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    mainApplication.service = mainApplication.service ?? [];
    const hasCardService = mainApplication.service.some(
      (s) => s.$?.['android:name'] === CARD_SERVICE_NAME,
    );
    if (!hasCardService) {
      mainApplication.service.push({
        $: {
          'android:name': CARD_SERVICE_NAME,
          'android:exported': 'true',
          'android:enabled': 'false',
          'android:permission': 'android.permission.BIND_NFC_SERVICE',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.nfc.cardemulation.action.HOST_APDU_SERVICE' } },
            ],
            category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          },
        ],
        'meta-data': [
          {
            $: {
              'android:name': 'android.nfc.cardemulation.host_apdu_service',
              'android:resource': '@xml/aid_list',
            },
          },
        ],
      });
    }

    return cfg;
  });

const withNfcHce = (config) => withHceManifest(withAidListXml(config));

module.exports = withNfcHce;
