-- Migration: 0001_alpha_baseline
-- Implements: /contracts/schema/0001-alpha-baseline.md
-- Reversal: drop the tables in reverse dependency order. See bottom of file.
--
-- This is a hand-written baseline migration. Future migrations are
-- generated by Drizzle from schema.ts files; we hand-write this one
-- so the schema is authoritative and reviewable from day one.

BEGIN;

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Helper: a column DEFAULT for UUIDv7-ish ids. We use uuid_generate_v4 for
-- now; replace with uuid_generate_v7 when an extension is available, or
-- generate UUIDv7 in application code for time-ordered ids.

-- =========================================================================
-- users
-- =========================================================================
CREATE TABLE users (
    id                       uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    email_encrypted          jsonb NOT NULL,
    email_hash               text NOT NULL UNIQUE,
    phone_encrypted          jsonb,
    phone_hash               text UNIQUE,
    display_name_encrypted   jsonb,
    mfa_enrolled             boolean NOT NULL DEFAULT false,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    deleted_at               timestamptz
);
CREATE INDEX users_email_hash_idx ON users (email_hash);
CREATE INDEX users_phone_hash_idx ON users (phone_hash);
CREATE INDEX users_active_idx ON users (id) WHERE deleted_at IS NULL;

-- =========================================================================
-- families
-- =========================================================================
CREATE TABLE families (
    id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name_encrypted  jsonb NOT NULL,
    created_by      uuid NOT NULL REFERENCES users(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);
CREATE INDEX families_created_by_idx ON families (created_by);
CREATE INDEX families_active_idx ON families (id) WHERE deleted_at IS NULL;

-- =========================================================================
-- family_caregivers
-- =========================================================================
CREATE TABLE family_caregivers (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_id   uuid NOT NULL REFERENCES families(id),
    user_id     uuid NOT NULL REFERENCES users(id),
    role        text NOT NULL CHECK (role IN ('admin', 'caregiver', 'readonly')),
    status      text NOT NULL CHECK (status IN ('active', 'revoked', 'pending')) DEFAULT 'pending',
    joined_at   timestamptz,
    revoked_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (family_id, user_id)
);
CREATE INDEX family_caregivers_user_id_idx ON family_caregivers (user_id);
CREATE INDEX family_caregivers_family_id_idx ON family_caregivers (family_id);

-- =========================================================================
-- children
-- =========================================================================
CREATE TABLE children (
    id                       uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_id                uuid NOT NULL REFERENCES families(id),
    display_name_encrypted   jsonb NOT NULL,
    date_of_birth_encrypted  jsonb NOT NULL,
    avatar_url               text,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    deleted_at               timestamptz
);
CREATE INDEX children_family_id_idx ON children (family_id);
CREATE INDEX children_active_idx ON children (id) WHERE deleted_at IS NULL;

-- =========================================================================
-- caregiver_child_access (per-child overrides; declared after children)
-- =========================================================================
CREATE TABLE caregiver_child_access (
    id                   uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_caregiver_id  uuid NOT NULL REFERENCES family_caregivers(id),
    child_id             uuid NOT NULL REFERENCES children(id),
    access_level         text NOT NULL CHECK (access_level IN ('full', 'readonly', 'none')),
    created_at           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (family_caregiver_id, child_id)
);

-- =========================================================================
-- invites
-- =========================================================================
CREATE TABLE invites (
    id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_id       uuid NOT NULL REFERENCES families(id),
    code            text NOT NULL UNIQUE,
    proposed_role   text NOT NULL CHECK (proposed_role IN ('admin', 'caregiver', 'readonly')),
    created_by      uuid NOT NULL REFERENCES users(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz NOT NULL,
    accepted_at     timestamptz,
    accepted_by     uuid REFERENCES users(id)
);
CREATE INDEX invites_family_id_idx ON invites (family_id);
CREATE INDEX invites_pending_idx ON invites (expires_at) WHERE accepted_at IS NULL;

-- =========================================================================
-- weight_records
-- =========================================================================
CREATE TABLE weight_records (
    id                      uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    child_id                uuid NOT NULL REFERENCES children(id),
    value_grams_encrypted   jsonb NOT NULL,
    recorded_at             timestamptz NOT NULL,
    recorded_by             uuid NOT NULL REFERENCES users(id),
    created_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX weight_records_child_recorded_idx
    ON weight_records (child_id, recorded_at DESC);

-- =========================================================================
-- medications (catalog)
-- =========================================================================
CREATE TABLE medications (
    id                       uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    generic_name             text NOT NULL,
    brand_name               text,
    concentration_label      text NOT NULL,
    concentration_mg_per_ml  numeric(8,3) NOT NULL,
    formulation              text NOT NULL CHECK (
        formulation IN ('liquid_suspension', 'infant_drops', 'chewable', 'oral_disintegrating')
    ),
    rx_status                text NOT NULL CHECK (rx_status IN ('otc', 'rx')) DEFAULT 'otc',
    min_age_months           integer NOT NULL,
    created_at               timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX medications_generic_idx ON medications (generic_name);
CREATE INDEX medications_rx_status_idx ON medications (rx_status);

-- =========================================================================
-- nfc_tags
-- =========================================================================
CREATE TABLE nfc_tags (
    id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tag_uid         text NOT NULL UNIQUE,
    family_id       uuid NOT NULL REFERENCES families(id),
    medication_id   uuid NOT NULL REFERENCES medications(id),
    status          text NOT NULL CHECK (status IN ('active', 'revoked', 'pending')) DEFAULT 'pending',
    label_encrypted jsonb,
    registered_by   uuid NOT NULL REFERENCES users(id),
    registered_at   timestamptz NOT NULL DEFAULT now(),
    revoked_at      timestamptz
);
CREATE INDEX nfc_tags_family_id_idx ON nfc_tags (family_id);

-- =========================================================================
-- dose_events
-- =========================================================================
CREATE TABLE dose_events (
    id                       uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_idempotency_key   uuid NOT NULL,
    child_id                 uuid NOT NULL REFERENCES children(id),
    medication_id            uuid NOT NULL REFERENCES medications(id),
    logged_by                uuid NOT NULL REFERENCES users(id),
    given_at                 timestamptz NOT NULL,
    amount_mg                numeric(8,3) NOT NULL,
    amount_volume_ml         numeric(8,3),
    unit_count               integer,
    note_encrypted           jsonb,
    status                   text NOT NULL CHECK (status IN ('active', 'superseded')) DEFAULT 'active',
    logged_at                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (client_idempotency_key, logged_by)
);
CREATE INDEX dose_events_child_given_idx
    ON dose_events (child_id, given_at DESC);
CREATE INDEX dose_events_logger_active_idx
    ON dose_events (logged_by, logged_at) WHERE status = 'active';

-- =========================================================================
-- dose_corrections
-- =========================================================================
CREATE TABLE dose_corrections (
    id                          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    original_dose_event_id      uuid NOT NULL REFERENCES dose_events(id),
    correction_dose_event_id    uuid NOT NULL REFERENCES dose_events(id),
    corrected_by                uuid NOT NULL REFERENCES users(id),
    reason_encrypted            jsonb,
    corrected_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dose_corrections_original_idx ON dose_corrections (original_dose_event_id);
CREATE INDEX dose_corrections_correction_idx ON dose_corrections (correction_dose_event_id);

-- =========================================================================
-- audit_events (hash-chained)
-- =========================================================================
CREATE TABLE audit_events (
    id              bigserial PRIMARY KEY,
    occurred_at     timestamptz NOT NULL DEFAULT now(),
    actor_user_id   uuid,
    actor_kind      text NOT NULL CHECK (actor_kind IN ('user', 'system', 'admin')),
    action          text NOT NULL,
    entity_type     text NOT NULL,
    entity_id       uuid,
    request_id      uuid,
    ip_hash         text,
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb,
    prev_hash       text,
    row_hash        text NOT NULL
);
CREATE INDEX audit_events_actor_idx ON audit_events (actor_user_id, occurred_at DESC);
CREATE INDEX audit_events_entity_idx ON audit_events (entity_type, entity_id);
CREATE INDEX audit_events_time_brin_idx ON audit_events USING brin (occurred_at);

-- The cappy_app role inserts and selects but cannot mutate or delete:
--   GRANT INSERT, SELECT ON audit_events TO cappy_app;
--   REVOKE UPDATE, DELETE ON audit_events FROM cappy_app;
-- Run separately after creating the role.

-- =========================================================================
-- idempotency_keys
-- =========================================================================
CREATE TABLE idempotency_keys (
    key            uuid NOT NULL,
    user_id        uuid NOT NULL REFERENCES users(id),
    response_status integer NOT NULL,
    response_body  jsonb NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    expires_at     timestamptz NOT NULL,
    PRIMARY KEY (key, user_id)
);
CREATE INDEX idempotency_keys_expires_idx ON idempotency_keys (expires_at);

COMMIT;

-- =========================================================================
-- ROLLBACK (manual)
-- =========================================================================
-- BEGIN;
-- DROP TABLE IF EXISTS idempotency_keys;
-- DROP TABLE IF EXISTS audit_events;
-- DROP TABLE IF EXISTS dose_corrections;
-- DROP TABLE IF EXISTS dose_events;
-- DROP TABLE IF EXISTS nfc_tags;
-- DROP TABLE IF EXISTS medications;
-- DROP TABLE IF EXISTS weight_records;
-- DROP TABLE IF EXISTS invites;
-- DROP TABLE IF EXISTS caregiver_child_access;
-- DROP TABLE IF EXISTS children;
-- DROP TABLE IF EXISTS family_caregivers;
-- DROP TABLE IF EXISTS families;
-- DROP TABLE IF EXISTS users;
-- COMMIT;
